# Generated by Django 4.2.4 on 2025-01-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
